### ISSUE TITLE
Missing Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [chromhelm/Arduino-libs#2]
Every Wire.beginTransmission() should be followed by Wire.write and be closed by Wire.endTransmission.

In the file "Arduino-libs/DS1621/DS1621.cpp" in the function begin(), the Wire.beginTransmission() is called before the previous has been transmitted with Wire.endTransmission(). To create a repeated start, the 'stop' parameter of Wire.endTransmission() can be set to 'false'.

**Comment by WilhelmWiens** [comment]
Hi added the Wire.endTransmission(). I tho not use repeated start since it is not necessary.
