### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [chromhelm/Arduino-libs#3]
In the file "Arduino-libs/HYB_HPSD3000/HYB_HPSD3000.cpp" in the function "getRawData()", there is a `delayMicroseconds(2);` during reading the data. There is however nothing to wait for. That delay can be removed.

**Comment by chromhelm** [comment]
It's right. I also remove the start and end transmission and the two unused variables.

**Comment by chromhelm** [comment]
It's right. I also remove the start and end transmission and the two unused variables.

**Comment by chromhelm** [comment]
It's right. I also remove the start and end transmission and the two unused variables.

**Comment by chromhelm** [comment]
It's right. I also remove the start and end transmission and the two unused variables.

**Comment by WilhelmWiens** [comment]
It's right. I also remove the start and end transmission and the two unused variables.

**Comment by Koepel** [comment]
Thanks. I saw your code used by someone else, that's why I scanned your code for the usage of the Wire library.

The forked I2C.cpp and I2C.h in "I2C-Master-Library" are from 2012. The normal Arduino Wire library supports a repeated start since years, and since 2012 a few bugs have been fixed. I didn't want to make an issue, perhaps you can add to the readme file there that the special I2C files are no longer needed.

**Comment by WilhelmWiens** [comment]
I think i just the repo since i do not use it anyway.
